### ISSUE TITLE
ValueError: Chromosome subsetting resulted in an empty DataFrame!

### ISSUE THREAD

**Issue by dzaccook** [bearbinxiong/DegNorm#13]
Hi,
When I run this package I got an error.
DegNorm (04/22/2019 09:26:57) ---- Begin genome annotation file processing...
DegNorm (04/22/2019 09:26:57) ---- Reading genome annotation file result.5.gff.
DegNorm (04/22/2019 09:26:57) ---- Subsetting exon data to 250 chromosomes:
	1, 10, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 11, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 12, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 13, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 14, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 15, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 16, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 17, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 19, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 2, 20, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 21, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 22, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 23, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 24, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 25, 250, 26, 27, 28, 29, 3, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 4, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 5, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 6, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 7, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 8, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 9, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99
Traceback (most recent call last):
  File "~/soft/anaconda3.6/envs/degnorm/bin/degnorm", line 11, in <module>
    load_entry_point('DegNorm==0.0.1', 'console_scripts', 'degnorm')()
  File "/~/soft/anaconda3.6/envs/degnorm/lib/python3.6/site-packages/DegNorm-0.0.1-py3.6.egg/degnorm/__main__.py", line 62, in main
    exon_df = gap.run()
  File "~/soft/anaconda3.6/envs/degnorm/lib/python3.6/site-packages/DegNorm-0.0.1-py3.6.egg/degnorm/gene_processing.py", line 172, in run
    exon_df = self.load()
  File "~/soft/anaconda3.6/envs/degnorm/lib/python3.6/site-packages/DegNorm-0.0.1-py3.6.egg/degnorm/gene_processing.py", line 44, in load
    exon_df = subset_to_chrom(exon_df, chrom=self.chroms)
  File "~/soft/anaconda3.6/envs/degnorm/lib/python3.6/site-packages/DegNorm-0.0.1-py3.6.egg/degnorm/utils.py", line 48, in subset_to_chrom
    raise ValueError('Chromosome subsetting resulted in an empty DataFrame!')
ValueError: Chromosome subsetting resulted in an empty DataFrame!

My sam files were acquired using TopHat2, and the gff file likes this,
1       EVM     mRNA    4431    5310    .       -       .       ID=evm.model.1.1;
1       EVM     CDS     4936    5310    .       -       0       Parent=evm.model.1.1;
1       EVM     CDS     4431    4529    .       -       0       Parent=evm.model.1.1;
1       EVM     mRNA    5755    7381    .       -       .       ID=evm.model.1.2;
1       EVM     CDS     6627    7381    .       -       0       Parent=evm.model.1.2;
1       EVM     CDS     5755    6553    .       -       1       Parent=evm.model.1.2;
Can you give me some help? Thank you!

**Comment by bearbinxiong** [comment]
This is because the standard input annotation file has to be gtf files, not gff. Gene names in the gtf file is needed for the read counts matrix and gene coverage. Please see this link https://useast.ensembl.org/info/website/upload/gff.html for the standard for gtf files.

This repository is not actively maintained. If you still have issues after using gtf files, please resubmit the issue under this repository: https://github.com/NUStatBioinfo/DegNorm

**Comment by bearbinxiong** [comment]
Also please make sure to use the most updated version of DegNorm in this fork: https://github.com/NUStatBioinfo/DegNorm

**Comment by dzaccook** [comment]
Thank you!
